const DARES = [
     "Do your best impression of a celebrity until someone guesses who it is.",
        "Let the group give you a new hairstyle using only their hands.",
        "Speak in an accent for the next three rounds.",
        "Let the group post one thing on your social media.",
        "Wear your clothes backwards for the next hour.",
        "Do 20 jumping jacks while singing the national anthem.",
        "Let someone style your hair with food items.",
        "Speak only in questions for the next 10 minutes.",
        "Do an interpretive dance of your favorite movie scene.",
        "Let the group choose three weird food combinations you must try.",
        "Call a random contact and sing 'Happy Birthday' to them.",
        "Do a handstand against the wall for 30 seconds.",
        "Let someone blindfold you and feed you mystery foods.",
        "Try to juggle three random objects for one minute.",
        "Do your best impression of each person in the room.",
        "Let the group write something on your forehead with marker.",
        "Attempt to touch your toes for 30 seconds without bending your knees.",
        "Do a catwalk down an imaginary runway with the group's commentary.",
        "Let someone give you a makeover with whatever they have on hand.",
        "Attempt to breakdance for one minute.",
        "Do a dramatic reading of a text conversation from your phone.",
        "Let the group control your next social media story for 24 hours.",
        "Attempt to moonwalk across the room.",
        "Do 15 squats while reciting the alphabet backwards.",
        "Let someone style an outfit for you from other people's clothes.",
        "Attempt to mimic a famous painting with your body.",
        "Do your best impression of a baby learning to walk.",
        "Let the group teach you a ridiculous dance you must perform.",
        "Attempt to recite a poem while hopping on one foot.",
        "Do a fashion show wearing the most mismatched outfit possible.",
        "Let someone draw a temporary tattoo on your arm.",
        "Attempt to do the worm (the dance move).",
        "Do a dramatic reenactment of a childhood memory.",
        "Let the group create a new signature move you must use all night.",
        "Attempt to hula hoop with an imaginary hula hoop.",
        "Do a news report about what's happening in the room right now.",
        "Let someone give you a new nickname that you must respond to.",
        "Attempt to do a magic trick with random objects from the room.",
        "Do 10 pushups right now.",
        "Sing the chorus of your favorite song as dramatically as possible.",
        "Let someone tickle you for 30 seconds without laughing.",
        "Make up a short rap about the person to your left.",
        "Do your best animal impression for one minute.",
        "Let the group choose an emoji you have to incorporate into every sentence for the next 5 minutes.",
        "Balance a spoon on your nose for 30 seconds.",
        "Do a silly dance for the next 30 seconds.",
        "Act out a scene from a movie without speaking until someone guesses it.",
        "Try to lick your elbow (it's impossible, but funny to watch!).",
        "Let someone draw on your face with a washable marker.",
        "Tell a funny story about yourself while standing on one leg."
]