const TRUTHS = [
    "What's the most embarrassing thing you've ever done?",
    "What's a secret you've never told anyone?",
    "Who was your first crush?",
     "What's the most embarrassing thing you've ever done?",
        "If you could swap lives with someone for a day, who would it be?",
        "What's a secret you've never told anyone?",
        "What's your biggest fear?",
        "What's the worst lie you've ever told?",
        "What's the most childish thing you still do?",
        "What's your most irrational fear?",
        "What's the worst date you've ever been on?",
        "What's the most illegal thing you've ever done?",
        "What's your biggest regret in life?",
        "What's something you've stolen and never returned?",
        "What's the worst thing you've ever said to someone?",
        "Have you ever cheated on a test or exam?",
        "What's the most inappropriate place you've fallen asleep?",
        "What's your most controversial opinion?",
        "What's something you judge people for but shouldn't?",
        "What's the biggest mistake you've made at work/school?",
        "What's the most embarrassing photo you have?",
        "What's something you're still angry about from years ago?",
        "What's the worst gift you've ever given someone?",
        "Have you ever pretended to like a gift you hated?",
        "What's the most childish fear you still have?",
        "What's something you've broken and never told anyone?",
        "What's the worst advice you've ever given?",
        "What's a habit you have that you know annoys people?",
        "What's something you should probably apologize for but haven't?",
        "What's the most entitled thing you've ever done?",
        "What's a lie you told that got way out of hand?",
        "What's something you're deeply insecure about?",
        "What's the most hypocritical thing you do?",
        "What's something you thought was cool but now cringe about?",
        "What's the pettiest thing you've ever done?",
        "Have you ever eavesdropped on a private conversation?",
        "What's something you've faked expertise in?",
        "What's the most awkward romantic encounter you've had?",
        "What's something you've done while drunk that you regret?",
        "What's the most dramatic thing you've done to get attention?",
        "What's something you'd never admit in real life?",
        "What's the worst first impression you've ever made?",
        "What's something you're secretly competitive about?",
        "What's the most selfish thing you've ever done?",
        "What's something you pretend to understand but don't?",
        "What's the most embarrassing thing in your search history?",
        "What's something you're secretly proud of?",
        "If you could be famous for one thing, what would it be?",
        "What's the silliest thing you've ever cried over?",
        "What's your guiltiest pleasure?",
        "What's the most trouble you've ever been in?",
        "What's something you pretend to like but actually hate?",
        "What's the weirdest habit you have?"
];